Name = input("Enter Customer Name: ")
Contact = input("Enter Contact Number: ")
Address = input("Enter Customer Address: ")
print("========================================")
print("Product 1")
Prod1 = input("Enter Product 1 Name: ")
Price1 = float(input("Enter Price: "))
Qty1 = int(input("Enter Quantity: "))
amount1 = float(Price1 * Qty1)
print(amount1)
print("========================================")
print("Product 2")
Prod2 = input("Enter Product 2 Name: ")
Price2 = float(input("Enter price: "))
Qty2 = int(input("Enter Quantity: "))
amount2 = float(Price2 * Qty2)
print(amount2)
print("========================================")
print("Product 3")
Prod3 = input("Enter Product 3 Name: ")
Price3 = float(input("Enter price: "))
Qty3 = int(input("Enter Quantity: "))
amount3 = float(Price3 * Qty3)
print(amount3)
print("========================================")
Discount = int(input("Enter Discount(%): "))
Subtotal = amount1 + amount2 + amount3 
print(Discount)
print(Subtotal)
print("========================================")
Discount = Subtotal * (Discount / 100)
Total = Subtotal - Discount
print("        ", "OFFICIAL STORE RECEIPT" ,"    ")
print("========================================")
print("Customer Name:" , Name)
print("Contact Number:" , Contact)
print("Address:" , Address)
print("----------------------------------------")
print(  "PRODUCT" , "       " ,    "PRICE" ,  "               "       "QTY")
print("----------------------------------------")
print( Prod1 ,"          ",    Price1 , "              ",    Qty1 )
print( Prod2 ,"   ",    Price2 , "               ",   Qty2 )
print( Prod3 ,"         ",    Price3 , "                ",   Qty3)
print("----------------------------------------")
print("Subtotal:" , Subtotal)
print("Discounted:" , Discount)
print("----------------------------------------")
print("Total of purchased:" ,Total)
print("========================================")
print("       ", "THANK YOU FOR PURCHASING!" "     ")
print("          ", "PLEASE COME AGAIN!!")
print()
print()
print()
print()